[project]
name = "hugging-face-text-to-text-service" # Edit this and remove comment

[tool.pytest.ini_options]
pythonpath = [".", "src"]
addopts = "--cov-config=.coveragerc --cov-report xml --cov-report term-missing --cov=./src"
